name: mlflow_fastapi
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
    - fastapi
    - uvicorn[standard]
    - click
    - scikit-learn==0.23.2
    - mlflow>=1.0
    - pandas
    - pytest
    - keras<2.6.0
    - scikit-learn
    - tensorflow!=2.5.*,!=2.6.*
    - autopep8
    - orjson
